include: package:lint/analysis_options.yaml

linter:
  rules:
    - parameter_assignments

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    missing_required_param: error
    parameter_assignments: error
    missing_return: error
    directives_ordering: ignore
    prefer_const_constructors_in_immutables: warning
    avoid_catching_errors: ignore
    avoid_positional_boolean_parameters: ignore
    avoid_classes_with_only_static_members: ignore