name: power_progress
description: Powerlifting workouts app.
publish_to: none
version: 2.35.4
environment:
  sdk: '>=2.7.0 <3.0.0'
scripts:
  watch: flutter pub run build_runner watch --delete-conflicting-outputs
dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.24.0
  bloc: ^6.0.0
  flutter_bloc: ^6.0.1
  get_it: ^4.0.3
  dartz: ^0.9.1
  logging: ^0.11.4
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  freezed_annotation: ^0.11.0
  numberpicker: ^1.2.0
  google_fonts: ^1.1.0
  package_info: ^0.4.1
  avatar_glow: ^1.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  flutter_launcher_icons: ^0.7.5
  lint: ^1.2.0
  build_runner: ^1.10.0
  hive_generator: ^0.7.0+2
  dartx: ^0.2.0
  freezed: ^0.11.4
dependency_overrides:
  path: 1.7.0
  quiver: 2.1.3
flutter_icons:
  android: true
  ios: true
  image_path: assets/launcher_logo.png
flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family:  CustomIcons
      fonts:
       - asset: fonts/CustomIcons.ttf
