name: power_progress
description: Powerlifting tracking app.
publish_to: none
version: 1.1.22
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.23.0
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0
  equatable: ^1.1.1
  get_it: ^4.0.1
  dartz: ^0.8.9
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
